import { Item, User, Conversation, Message } from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ahmad Rizki',
    email: 'ahmad.rizki@student.president.ac.id',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Siti Nurhaliza',
    email: 'siti.nurhaliza@student.president.ac.id',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siti',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    name: 'Dr. Budi Santoso',
    email: 'budi.santoso@president.ac.id',
    role: 'lecturer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Budi',
    createdAt: new Date('2023-08-01'),
  },
  {
    id: '4',
    name: 'Admin User',
    email: 'admin@president.ac.id',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    createdAt: new Date('2023-01-01'),
  },
];

// Mock Items
export const mockItems: Item[] = [
  {
    id: '1',
    type: 'lost',
    title: 'Black Leather Wallet',
    description: 'Lost my black leather wallet near the Engineering building. Contains student ID and some cash. Please contact me if found.',
    category: 'personal',
    location: 'academic',
    locationDetail: 'Engineering Building, Floor 2',
    date: new Date('2024-01-25'),
    status: 'active',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=400'],
    userId: '1',
    userName: 'Ahmad Rizki',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '2',
    type: 'found',
    title: 'Apple AirPods Pro',
    description: 'Found white AirPods Pro case near the library entrance. Currently held at the security office.',
    category: 'electronics',
    location: 'common',
    locationDetail: 'University Library, Main Entrance',
    date: new Date('2024-01-24'),
    status: 'active',
    images: ['https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400'],
    userId: '2',
    userName: 'Siti Nurhaliza',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siti',
    createdAt: new Date('2024-01-24'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: '3',
    type: 'lost',
    title: 'Blue Notebook with Lecture Notes',
    description: 'Lost a blue spiral notebook containing important lecture notes for Computer Science 301. Last seen in Room 405.',
    category: 'academic',
    location: 'academic',
    locationDetail: 'Science Building, Room 405',
    date: new Date('2024-01-23'),
    status: 'active',
    images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400'],
    userId: '1',
    userName: 'Ahmad Rizki',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad',
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: '4',
    type: 'found',
    title: 'Student ID Card',
    description: 'Found a President University student ID card at the cafeteria. Name starts with "M".',
    category: 'personal',
    location: 'food',
    locationDetail: 'Main Cafeteria, Near Cashier',
    date: new Date('2024-01-22'),
    status: 'claimed',
    images: ['https://images.unsplash.com/photo-1578670812003-60745e2c2ea9?w=400'],
    userId: '3',
    userName: 'Dr. Budi Santoso',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Budi',
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-26'),
  },
  {
    id: '5',
    type: 'lost',
    title: 'Silver MacBook Charger',
    description: 'Lost my MacBook charger in the dormitory common room. 67W USB-C charger.',
    category: 'electronics',
    location: 'dormitory',
    locationDetail: 'Dormitory Block A, Common Room',
    date: new Date('2024-01-21'),
    status: 'active',
    images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400'],
    userId: '2',
    userName: 'Siti Nurhaliza',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siti',
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '6',
    type: 'found',
    title: 'Black Umbrella',
    description: 'Found a black automatic umbrella left in the food court area after the rain.',
    category: 'miscellaneous',
    location: 'food',
    locationDetail: 'Food Court, Table Area',
    date: new Date('2024-01-20'),
    status: 'active',
    images: ['https://images.unsplash.com/photo-1534309466160-70b22cc6252c?w=400'],
    userId: '1',
    userName: 'Ahmad Rizki',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
];

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: '1',
    itemId: '2',
    itemTitle: 'Apple AirPods Pro',
    participants: ['1', '2'],
    lastMessage: {
      id: 'm3',
      conversationId: '1',
      senderId: '2',
      senderName: 'Siti Nurhaliza',
      content: 'Yes, you can pick it up at the security office tomorrow.',
      createdAt: new Date('2024-01-25T14:30:00'),
      read: false,
    },
    unreadCount: 1,
    createdAt: new Date('2024-01-25'),
  },
];

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: 'm1',
    conversationId: '1',
    senderId: '1',
    senderName: 'Ahmad Rizki',
    content: 'Hi, I think those are my AirPods! Can I come pick them up?',
    createdAt: new Date('2024-01-25T10:00:00'),
    read: true,
  },
  {
    id: 'm2',
    conversationId: '1',
    senderId: '2',
    senderName: 'Siti Nurhaliza',
    content: 'Sure! Can you describe the case or provide any proof of ownership?',
    createdAt: new Date('2024-01-25T10:15:00'),
    read: true,
  },
  {
    id: 'm3',
    conversationId: '1',
    senderId: '1',
    senderName: 'Ahmad Rizki',
    content: 'The case has a small scratch on the right side, and they are paired with my iPhone.',
    createdAt: new Date('2024-01-25T10:30:00'),
    read: true,
  },
  {
    id: 'm4',
    conversationId: '1',
    senderId: '2',
    senderName: 'Siti Nurhaliza',
    content: 'Yes, you can pick it up at the security office tomorrow.',
    createdAt: new Date('2024-01-25T14:30:00'),
    read: false,
  },
];

// Statistics
export const mockStats = {
  totalItems: 156,
  itemsRecovered: 89,
  activeListings: 67,
  successRate: 57,
};

// Current logged in user (mock)
export const currentUser: User | null = null;
